describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://quiz-ppt.vercel.app/')
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(2)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()
    cy.get('.text-center > :nth-child(3) > :nth-child(1)').click()
    cy.get('.button').click()

  })
})