name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v1
        with:
          java-version: 23

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test